pipeline {
    agent {
      label 'AGENT-1'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }

    // environment {
    //     DEBUG = 'true'
    // }

    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'select the action')
    }
    stages {
        stage('init and plan') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 50-eks
                        terraform init -reconfigure
                        terraform plan -out=tfplan
                    """

            }
        }
        stage('Apply and Destroy') {
            // input {
            //     message "Should we continue to ${params.ACTION}"
            //     ok "Yes, we should."
            // }

            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 50-eks
                        if [ ${params.ACTION} == 'apply' ]
                        then
                            terraform apply --auto-approve

                        elif [ ${params.ACTION } == 'destroy' ]
                        then
                            terraform destroy --auto-approve
                        fi
                    """
                }
            }
        }
    }

    post {
        always{
            echo "This sections runs always"
            deleteDir()
        }
        success {
            echo "Build Successful"
        }
        failure {
            echo "Build Failed"
        }
    }
}
